name: built_mirrors_example
version: 0.0.1

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_mirrors:
    path: ../

dev_dependencies:
  build_runner: any
  test: any
  build_test: any
  build_web_compilers: any