name: built_mirrors_example
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  built_mirrors:
    path: ../

dev_dependencies:
  build_runner: any
  test: any
  build_test: ^2.1.7
  build_web_compilers: any
