name: built_mirrors_example
version: 0.0.1

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  built_mirrors:
    path: ../

dev_dependencies:
  build_runner: ^0.7.0
  test: ^0.12.0
  build_test: ^0.10.1
  build_web_compilers: ^0.3.0