name: built_mirrors_example
version: 0.0.1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  built_mirrors:
    path: ../

dev_dependencies:
  build_runner: any
  test: any
  build_test: ^2.1.5
  build_web_compilers: any
