targets:
  $default:
    builders:
      built_mirrors:
        generate_for:
          - test/**
builders:
  built_mirrors:
    import: package:built_mirrors/builder.dart
    builder_factories: [builder]
    auto_apply: dependents
    build_extensions:
      .dart: [.built_mirrors.g.part]
    applies_builders: [source_gen|combining_builder]
