builders:
  built_mirrors_builder:
    target: built_mirrors_builder
    import: package:built_mirrors/builder.dart
    builder_factories: [builder]
    build_to: source
    auto_apply: dependents
    build_extensions:
      .dart: [.g.dart]