name: built_mirrors
version: 1.0.0
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
homepage: https://github.com/dart-league/built_mirrors

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  source_gen: ^1.2.1
  build: ^2.2.1
  analyzer: ^3.3.1
#  built_mirrors_core: ^0.10.6
#  built_mirrors_core:
#    path: ../built_mirrors_core

dev_dependencies:
  test: ^1.20.2
  build_test: ^2.1.5
  build_runner: ^2.1.8
