name: built_mirrors
version: 2.0.1
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
homepage: https://github.com/dart-league/built_mirrors

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  source_gen: ^1.3.2
  build: ^2.4.0
  analyzer: ^5.13.0
  collection: ^1.17.2
#  built_mirrors_core: ^0.10.6
#  built_mirrors_core:
#    path: ../built_mirrors_core

dev_dependencies:
  test: ^1.24.3
  build_test: ^2.1.7
  build_runner: ^2.4.4
