name: built_mirrors
version: 0.10.0
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/built_mirrors

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  source_gen: ^0.9.0
  build: ^0.12.0
  analyzer: ^0.32.0
  built_mirrors_core: ^0.10.0
#  built_mirrors_core:
#    path: ../built_mirrors_core


dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.1
  build_runner: ^0.9.0