name: built_mirrors
version: 0.5.1
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/built_mirrors

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  source_gen: ^0.7.0
  build: ^0.10.0
  build_runner: ^0.4.0
  analyzer: ^0.30.0

dev_dependencies:
  test: ^0.12.0
  build_test: ^0.7.0
