name: built_mirrors
version: 0.13.0
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
homepage: https://github.com/dart-league/built_mirrors

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  source_gen: ^0.9.0
  build: ^1.0.1
  analyzer: ^0.40.0
#  built_mirrors_core: ^0.10.6
#  built_mirrors_core:
#    path: ../built_mirrors_core

dev_dependencies:
  test: ^1.0.0
  build_test: ^1.2.0
  build_runner: ^1.0.0
