name: built_mirrors
version: 0.0.2
description: generates `ClassMirror` from classes annotated with `@reflectable` or `@Reflectable()`
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/built_mirrors

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  source_gen: ^0.5.3
  build_runner: ^0.1.1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  build_test: ^0.3.1
